title: Yoelable
# email:
description: >- # this means to ignore newlines until "baseurl:"
  Follow along as I write my heart out and explore the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  Aspiring-Writer

author: Y.A. Olson
avatar: /assets/images/avatar.jpg
location: Queens, New York, US

paginate: 7
permalink: /:categories/:title.html
future: false

prose:
  siteurl: 'https://aspiring-writer.github.io'
  media: 'assets/images'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "date"
      	field:
          element: "number"
          label: "Date"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Choose Categories"
          options:
            - name: "Poem"
              value: "poetry"
            - name: "Article"
              value: "articles"
            - name: "Devotional"
              value: "devotionals"
            - name: "Tutorial"
              value: "tutorials"
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  
remote_theme: ngzhio/jekyll-theme-hamilton

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  
keep_files:
  - assets/
