title: Diary of a Writing Addict
# email:
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://aspiring-writer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  Aspiring-Writer

author: Y.A. Olson
avatar: /assets/images/avatar.jpg
location: America/New_York

paginate: 7

permalink: /:categories/:title.html

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  
remote_theme: ngzhio/jekyll-theme-hamilton


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  
keep_files:
  - assets/