title: "An Aspiring Writer's Journal"
#email:
description: >-
  Follow along as I write my heart out and explore the unknown depths of my imagination.
  (Icons made by Eucalyp from www.flaticon.com)
baseurl: "" 
url: "https://aspiring-writer.github.io"
#twitter_username: jekyllrb
github_username:  Aspiring-Writer

author: Bravisha Skietano
avatar: /assets/avatar.png
location: Who knows?...

paginate: 7
permalink: /:categories/:title.html
future: false

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
  
remote_theme: ngzhio/jekyll-theme-hamilton

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  
keep_files:
  - assets/
