title: "An Aspiring Writer's Haven"
description: >-
  Follow along as I write my heart out and explore the unknown depths of my imagination.
baseurl: "/"
url: "https://aspiring-writer.github.io"
author: Yoela Olson
logo: https://www.gravatar.com/avatar/8305681be23372ec3c774233546f849f?s=500

defaults:
  -
    scope:
      path: "_pages"
    values:
      layout: "page"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      
paginate: 7
permalink: /:categories/:title.html
future: false

# Build settings
theme: null
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - _pages
  
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
